clear all
clc
close all

% filter_name_list = {'all_trials_coef1_hVis2_FR1_multiUnits';...
%     'all_trials_coef1_hVis2_FR1_singleUnits';...
%     'all_trials_coef1_hVis2_FR1_multiUnits_sizeControl';...
%     'all_trials_coef1_hVis2_FR1_singleUnits_sizeControl'};
%filter_name_list = {'all_trials_coef1_hVis2_FR1_subSamples'};
% filter_name_list = {'all_trials_coef1_hVis2_FR1_hVisOri2_FROri2_sizeControl'};
%filter_name_list = {'all_trials_coef1_hVis2_FR1_hVisOri2_FROri2_subSamples'};

% filter_name_list = [{'all_trials_coef1_hVis2_FR1'};...
%                     gen_filter_name_list('projectedEyeposition');...
%                     gen_filter_name_list('distanceEyePosition');...
%                     gen_filter_name_list('eyeVelocity');...
%                     gen_filter_name_list('pupil')];

% filter_name_list = {'all_trials_coef1_hVis2_FR1_sizeControl';...
%                     'all_trials_coef1_hVis2_FR1_multiUnits_sizeControl';...
%                     'all_trials_coef1_hVis2_FR1_singleUnits_sizeControl'};
%% run 1
% filter_name_list = {'all_trials_lower_stimulusdprime_sizeControl';'all_trials_higher_stimulusdprime_sizeControl';...
%     'choice_1_coef1_hVis2_FR1_sizeControl';'choice_2_coef1_hVis2_FR1_sizeControl'};

filter_name_list = {'all_trials_coef1_hVis2_FR1_interleaved_sizeControl'};

runOptions.doRun = 1;
runOptions.doRuncross = 0;

runOptions.doReplace = 1;
runOptions.doReplace_cross = 0;

runOptions.doOrganize = 0;
runOptions.doOrganizeCross = 0;

runOptions.doCombineAcrossCoherence = 0;


runOptions.doTask = 1;
runOptions.doOrientation = 1;


runOptions.doMultiple_timebin = 1;

runOptions.timebinsize = 200;

combineOptions = struct();

for n = 1:numel(filter_name_list)
    filter_name = filter_name_list{n};
    run_directFisherInfoEstimate_versionControl(filter_name,runOptions,combineOptions);
end

% %% run 2
% filter_name_list = {'all_trials_coef1_hVis2_FR1_hVisOri2_FROri2_sizeControl'};
% runOptions.doRun = 1;
% runOptions.doRuncross = 0;
% 
% runOptions.doReplace = 1;
% runOptions.doReplace_cross = 0;
% 
% runOptions.doOrganize = 0;
% runOptions.doOrganizeCross = 0;
% 
% runOptions.doCombineAcrossCoherence = 0;
% 
% 
% runOptions.doTask = 1;
% runOptions.doOrientation = 1;
% 
% runOptions.doMultiple_timebin = 1;
% runOptions.timebinsize = 400;
% 
% combineOptions = struct();
% 
% for n = 1:numel(filter_name_list)
%     filter_name = filter_name_list{n};
%     run_directFisherInfoEstimate_versionControl(filter_name,runOptions,combineOptions);
% end

%%
function filter_name_list = gen_filter_name_list(option)
switch option
    case 'eyeVelocity'
        filter_name_list = {'eyeVelocity_high_prctile40_coef1_hVis2_FR1';...
            'eyeVelocity_high_prctile50_coef1_hVis2_FR1';...
            'eyeVelocity_high_prctile60_coef1_hVis2_FR1';...
            'eyeVelocity_high_prctile70_coef1_hVis2_FR1';...
            'eyeVelocity_high_prctile80_coef1_hVis2_FR1';...
            'eyeVelocity_high_prctile90_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile40_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile50_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile60_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile70_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile80_coef1_hVis2_FR1';...
            'eyeVelocity_low_prctile90_coef1_hVis2_FR1'};
    case 'pupil'
        filter_name_list = {'pupilSize_high_prctile40_coef1_hVis2_FR1';...
            'pupilSize_high_prctile50_coef1_hVis2_FR1';...
            'pupilSize_high_prctile60_coef1_hVis2_FR1';...
            'pupilSize_high_prctile70_coef1_hVis2_FR1';...
            'pupilSize_high_prctile80_coef1_hVis2_FR1';...
            'pupilSize_high_prctile90_coef1_hVis2_FR1';...
            'pupilSize_low_prctile40_coef1_hVis2_FR1';...
            'pupilSize_low_prctile50_coef1_hVis2_FR1';...
            'pupilSize_low_prctile60_coef1_hVis2_FR1';...
            'pupilSize_low_prctile70_coef1_hVis2_FR1';...
            'pupilSize_low_prctile80_coef1_hVis2_FR1';...
            'pupilSize_low_prctile90_coef1_hVis2_FR1'};

    case 'distanceEyePosition'
        filter_name_list = {'distanceEyePosition_center_prctile40_coef1_hVis2_FR1';...
            'distanceEyePosition_center_prctile50_coef1_hVis2_FR1';...
            'distanceEyePosition_center_prctile60_coef1_hVis2_FR1';...
            'distanceEyePosition_center_prctile70_coef1_hVis2_FR1';...
            'distanceEyePosition_center_prctile80_coef1_hVis2_FR1';...
            'distanceEyePosition_center_prctile90_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile40_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile50_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile60_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile70_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile80_coef1_hVis2_FR1';...
            'distanceEyePosition_surround_prctile90_coef1_hVis2_FR1'};
    case 'projectedEyeposition'
        filter_name_list = {'projectedEyePosition_center_prctile40_coef1_hVis2_FR1';...
            'projectedEyePosition_center_prctile50_coef1_hVis2_FR1';...
            'projectedEyePosition_center_prctile60_coef1_hVis2_FR1';...
            'projectedEyePosition_center_prctile70_coef1_hVis2_FR1';...
            'projectedEyePosition_center_prctile80_coef1_hVis2_FR1';...
            'projectedEyePosition_center_prctile90_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile40_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile50_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile60_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile70_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile80_coef1_hVis2_FR1';...
            'projectedEyePosition_surround_prctile90_coef1_hVis2_FR1'};
end
end